/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.spark.sql.catalyst.analysis

import org.apache.spark.sql.catalyst.plans.logical.AlterViewAs
import org.apache.spark.sql.catalyst.plans.logical.LogicalPlan
import org.apache.spark.sql.catalyst.plans.logical.views.CreateIcebergView
import org.apache.spark.sql.catalyst.plans.logical.views.ResolvedV2View
import org.apache.spark.sql.connector.catalog.ViewCatalog
import org.apache.spark.sql.execution.command.ViewHelper

object CheckViews extends (LogicalPlan => Unit) {

  import org.apache.spark.sql.connector.catalog.CatalogV2Implicits._

  override def apply(plan: LogicalPlan): Unit = {
    plan foreach {
      // RewriteViewCommands replaces Spark's CreateView before CheckViewReferences runs, so apply
      // Spark's shared post-analysis checks to the Iceberg node here. Spark expands referenced
      // views into logical View nodes for cycle detection. Spark's V2CreateViewPreparation still
      // checks column counts and duplicate query column names during execution.
      case c: CreateIcebergView if c.isAnalyzed =>
        c.child match {
          case resolvedIdent @ ResolvedIdentifier(_: ViewCatalog, _) =>
            val viewIdent: Seq[String] =
              resolvedIdent.catalog.name() +: resolvedIdent.identifier.asMultipartIdentifier
            ViewHelper.verifyTemporaryObjectsNotExists(
              isTemporary = false,
              viewIdent,
              c.query,
              c.referredTempFunctions)
            ViewHelper.verifyAutoGeneratedAliasesNotExists(c.query, isTemporary = false, viewIdent)
            if (c.replace) {
              ViewHelper.checkCyclicViewReference(c.query, Seq(viewIdent), viewIdent)
            }

          case _ => // OK
        }

      case AlterViewAs(ResolvedV2View(_, _, _), _, _, _, _) =>
        throw new IcebergAnalysisException(
          "ALTER VIEW <viewName> AS is not supported. Use CREATE OR REPLACE VIEW instead")

      case _ => // OK
    }
  }
}
